server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        # ---------- USER ----------
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: user-docs
          uri: lb://user-service
          predicates:
            - Path=/v3/api-docs/user
          filters:
            - RewritePath=/v3/api-docs/user,/v3/api-docs

        # ---------- WARDROBE ----------
        - id: wardrobe-service
          uri: lb://wardrobe-service
          predicates:
            - Path=/items/**

        - id: wardrobe-docs
          uri: lb://wardrobe-service
          predicates:
            - Path=/v3/api-docs/wardrobe
          filters:
            - RewritePath=/v3/api-docs/wardrobe,/v3/api-docs

        # ---------- OUTFIT ----------
        - id: outfit-service
          uri: lb://outfit-service
          predicates:
            - Path=/outfits/**

        - id: outfit-docs
          uri: lb://outfit-service
          predicates:
            - Path=/v3/api-docs/outfit
          filters:
            - RewritePath=/v3/api-docs/outfit,/v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: User Service
        url: /v3/api-docs/user

      - name: Wardrobe Service
        url: /v3/api-docs/wardrobe

      - name: Outfit Service
        url: /v3/api-docs/outfit

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
