server:
  port: 8082

spring:
  application:
    name: wardrobe-service
  r2dbc:
    url: r2dbc:postgresql://postgres-wardrobe:5432/wardrobe_db
    username: wardrobe
    password: wardrobe
  flyway:
    enabled: true
    url: jdbc:postgresql://postgres-wardrobe:5432/wardrobe_db
    user: wardrobe
    password: wardrobe
    locations: classpath:db/migration

springdoc:
  api-docs:
    path: /v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
    instances:
      wardrobe-service:
        baseConfig: default

  timelimiter:
    configs:
      default:
        timeoutDuration: 2s
        cancelRunningFuture: true
    instances:
      wardrobe-service:
        baseConfig: default

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    circuitbreakers:
      enabled: true
